#### Làm việc với ma trận 

In [2]:
import numpy as np

#### Khởi tạo 1 ma trận

In [2]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


####  Ma trận đơn vị và ma trận đường chéo 

In [3]:
a = np.diag([1,2,3,4,5,6,7,8,9],k = -1)
print(a)

[[0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 6 0 0 0 0]
 [0 0 0 0 0 0 7 0 0 0]
 [0 0 0 0 0 0 0 8 0 0]
 [0 0 0 0 0 0 0 0 9 0]]


#### Truy cập vòa từng phần tử của ma trân

In [4]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[4,7,9]])
x.shape
i=x.shape[0]
print(i)
print(x[:,0])
print(x[1,0])
print(x[2,0])
print(x[3,0])
print(x[0,2])
print(x[1,2])
print(x[2,2])
print(x[3,2])
a = np.sum(x[0,0]+x[1,0]+x[2,0]+x[3,0]+x[0,2]+x[1,2]+x[2,2]+x[3,2])
a

4
[1 4 7 4]
4
7
4
3
6
9
9


43

In [5]:
D = np.array([[1,2,3],[4,5,6],[7,8,9],[4,7,9]])
def myfunc(x):
    i = x.shape[0]
    j = x.shape[1]
    A = 0
    n = 0
    m = 0
    while m < j :
        for n in range(0,i):
                A = A+ x[n,m]        
        m += 2
    print(A)
myfunc(D)

43


#### Truy cập vào nhiều phần tử của ma trận

In [6]:
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
def myfunc(x):
    i = x.shape[0]
    j = x.shape[1]
    A = 0
    m = 0
    while m < j:
        n = 0
        while n < i :
            A = A+ x[n,m]
            n = n + 2
        m = m + 2    
    print(A)  
myfunc(B)    
            

24


#### np.sum, np.min, np.max, np.mean cho mảng nhiều chiều

In [7]:
H = np.array([[1, 2, 3, 4], [4, 3, 7, 8], [9, 6, 7, 7]])
def myfunc(x):
    i = x.shape[0]
    j = x.shape[1]
    A = 0
    x = 0
    while x < i:
        A = np.max(H[x,:]) - np.min(H[x,:]) + A 
        x += 1
    print(A)
myfunc(H)


11


#### Các phép toán tác động đến mọi phần tử của ma trận

In [17]:
F = np.array([[1, 3], [2, 5],[6,9]])
def norm_fro(x):
    i = x.shape[0]
    j = x.shape[1]
    A = 0
    y = 2
    m = 0
    n = 0
    while  m < j :
        for n in range(0,i): 
            A = np.sum(x[n,m]**y) + A
        m += 1  
        h = np.sqrt(A)
    print(h)    
norm_fro(F) 

12.489995996796797


In [27]:
A = np.array([[1., 5], [2, 3]])
B = np.array([[5., 2], [4, 3]])     
def dist_fro(x):
    i = x.shape[0]
    j = x.shape[1]
    C = 0
    D = 0
    m = 0 
    n = 0 
    q = 0 
    w = 0
    while m  < j:
        for n in range(0,i): 
            C = np.sum(x[n,m]**2) + C
            m += 1
            h = np.sqrt(C)
    print(h)
dist_fro(A)
    

3.1622776601683795


In [5]:
np.random.seed(1) 