## Khởi tạo mảng 1 chiều

In [3]:
import numpy
import numpy as np

#### khai báo 1 vector 

In [4]:
x = np.array([1 ,2,3,4,5,6,7,8,9,10])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Khởi tạo 1 mảng 1 chiều đặc biệt

In [5]:
x = np.arange(2**0,2**10,1)
x

array([   1,    2,    3, ..., 1021, 1022, 1023])

##### Bài 2 

In [6]:
x = np.array([3,3,3,3,3,3,3,3,3,1.5])
x

array([3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 1.5])

#### Truy cập mảng 1 chiều

In [7]:
x = np.array ([1,3,5])
for x2 in x :
    x2 = np.mean(x)
x[[0,1,2]]=x2
print(x)
print('trung binh cong',x2)

[3 3 3]
trung binh cong 3.0


#### Truy cập nhiều phần tử của mảng 1 chiều

In [8]:
x = np.arange(2,0,-0.5)
x


array([2. , 1.5, 1. , 0.5])

#### Tính toán giữa các mảng 1 chiều và số vô hướng 

In [9]:
x = np.array([4,5,7])
pi = 3.14
y = pi/2 - x
print(y)
z = np.cos(x) - np.sin(x)
print(z)
print('Tổng z =',np.sum(z))
    

[-2.43 -3.43 -5.43]
[0.10315887 1.24258646 0.09691566]
Tổng z = 1.4426609901951966


#### Norm 1

In [10]:
x = np.array([5,324,-6456,-7688])
a = np.abs(x)
print('Tổng giá trị tuyệt đối =',np.sum(a))

Tổng giá trị tuyệt đối = 14473


 #### Hàm Softmax cho mảng một chiều

In [11]:
x = np.array([1,2,3,4,5,6])
a_exp = np.exp(x)
print([round(i,2) for i in a_exp])
j = 0
Y = 2
while j<10:
    Y = Y + j
    j = j+ 1
print(Y)


[2.72, 7.39, 20.09, 54.6, 148.41, 403.43]
47


#### Tích vô hướng của hai vectors

In [15]:
x = np.arange(5)
y = np.ones(5)
z = np.sum(x*y)
print(z)

10.0


#### min, max,armin,argmax của mảng 1 chiều

In [24]:
a = np.arange(5)
a[-1] =-2
a.argmin()


4